version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: lending-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "55432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: lending-trx-app
    depends_on:
      - postgres
    environment:
      PG_DSN: "postgres://postgres:password@postgres:5432/postgres?sslmode=disable"
      WEBHOOK_AUTH_TOKEN: "mysecrettoken"
      PORT: "8080"
    restart: unless-stopped
    ports:
      - "28080:8080"

volumes:
  pgdata: 